name: admin_timesabai
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  google_fonts: 6.2.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  flutter_spinkit: ^5.2.1
  adaptive_dialog: ^2.2.1+2
  flutter_speed_dial: ^7.0.0
  loading_animation_widget: ^1.3.0
  intl: ^0.19.0
  simple_month_year_picker: ^1.0.5
  flutter_launcher_icons: ^0.14.1
  status_alert: ^1.0.1
  pdf: ^3.11.1
  printing: ^5.13.3
  flutter_pdfview: ^1.3.3
  signature: ^5.5.0
  image_picker: ^1.1.2
  path: ^1.8.0
  animated_text_kit: ^4.2.2
  syncfusion_flutter_signaturepad: ^27.1.53
  syncfusion_flutter_pdf: ^27.1.53
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  dio: ^5.7.0
  syncfusion_flutter_pdfviewer: ^27.1.53
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  http: ^1.2.2
  cached_network_image: ^3.4.1
  lottie: ^3.1.3
  panara_dialogs: ^0.1.5
  font_awesome_flutter: ^10.5.0
  ionicons: ^0.2.2
  flutter_staggered_grid_view: ^0.6.0
  transparent_image: ^2.0.1
  widget_mask: ^1.0.0+0
  logger: ^2.4.0
  syncfusion_flutter_charts: ^27.2.5
  crypto: ^3.0.3
  carousel_slider: ^5.0.0
  flutter_animate: ^4.5.2
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/play_store.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/play_store.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/play_store.png
    - assets/icons/images.png
    - assets/fonts/

  fonts:
    - family: BoonHome
      fonts:
        - asset: assets/fonts/BoonHome-400.ttf
    - family: OrangesPersonalUseBold
      fonts:
        - asset: assets/fonts/OrangespersonaluseBold-YzBEv.otf
